INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('server_address','http://localhost:8080/HMPLAT/','产权服务器地址');

INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('allow_project_pledge_sale','no','在建工程房屋是否可签约 yes   no');



ALTER TABLE CONTRACT.HOUSE_CONTRACT ADD GROUP_ID VARCHAR(32) NOT NULL;


CREATE TABLE CONTRACT.SALE_PROXY_PERSON
(
  ID varchar(32) NOT NULL,
  GROUP_ID varchar(32) NOT NULL,
  ID_NO varchar(100) NOT NULL,
  ID_TYPE varchar(32) NOT NULL,
  NAME varchar(50) NOT NULL,
  PHONE varchar(15) NOT NULL,
  CREATE_DATE timestamp NOT NULL,
  DISABLED boolean NOT NULL,
  PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE CONTRACT.SALE_PROXY_PERSON
ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
  ON UPDATE RESTRICT
  ON DELETE RESTRICT
;

