USE CONTRACT;

CREATE TABLE CONTRACT.ARTICLE
(
	ID varchar(32) NOT NULL,
	MAIN_TITLE varchar(256) NOT NULL,
	SUB_TITLE varchar(512),
	CATEGORY varchar(32) NOT NULL,
	PUBLISH_TIME timestamp NOT NULL,
	CONTEXT longtext NOT NULL,
	FIX_TOP boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.ARTICLE_CATEGORY
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	PRI int NOT NULL,
	TYPE varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE CONTRACT.SYSTEM_PARAM CHANGE VALUE VALUE LONGTEXT;
ALTER TABLE CONTRACT.SYSTEM_PARAM ADD TYPE VARCHAR(16) NOT NULL;
UPDATE SYSTEM_PARAM set TYPE = 'STRING';

INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('web_url','STRING','www.fcfcdjw.com','网站域名');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('web_name','STRING','辽宁省凤城房产登记网','网站名称');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('address','STRING','凤城市振兴街8号','地址');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('post_code','STRING','118100','邮编');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('tel','STRING','(0415)8122071','电话');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('e_mail','STRING','fc_fangchan@163.com','电邮');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('head_logo_url','IMG','http://localhost:8080/HouseSaleContract_SNAPSHOT/img/cms/sitelogo.png','网站主图标地址');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('foot_logo_url','IMG','http://localhost:8080/HouseSaleContract_SNAPSHOT/img/cms/housing_authority_footer_logo.png','网站脚图标地址');

INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('cms_mgr_password','STRING','FcCMS001','网站管理密码');

INSERT CONTRACT.ARTICLE_CATEGORY(ID,NAME,PRI,TYPE,DESCRIPTION) VALUES ('events','事件&通知',0,'Events','事件&通知');
INSERT CONTRACT.ARTICLE_CATEGORY(ID,NAME,PRI,TYPE,DESCRIPTION) VALUES ('welcome','Welcome',0,'Welcome','首页文章');
INSERT CONTRACT.ARTICLE(ID,MAIN_TITLE,CATEGORY,PUBLISH_TIME,FIX_TOP,VIEW_TYPE) VALUES ('welcome','首页文章','welcome',now(),false,'TEXT');
