INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('nginx_address','STRING','http://localhost:6699','API服务器地址');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('database_version','STRING','1.3','数据库版本');


CREATE TABLE CONTRACT.SCHOOL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SELL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;