USE CONTRACT;

CREATE TABLE CONTRACT.ARTICLE
(
	ID varchar(32) NOT NULL,
	MAIN_TITLE varchar(256) NOT NULL,
	SUB_TITLE varchar(512),
	CATEGORY varchar(32) NOT NULL,
	PUBLISH_TIME timestamp NOT NULL,
	CONTEXT longtext NOT NULL,
	FIX_TOP boolean NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

CREATE TABLE CONTRACT.ARTICLE_CATEGORY
(
	ID varchar(32) NOT NULL,
	NAME varchar(32) NOT NULL,
	PRI int NOT NULL,
	TYPE varchar(16) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


ALTER TABLE CONTRACT.SYSTEM_PARAM CHANGE VALUE VALUE VARCHAR(512);

INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('web_url','www.fcfcdjw.com','网站域名');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('web_name','辽宁省凤城房产登记网','网站名称');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('address','凤城市振兴街8号','地址');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('post_code','118100','邮编');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('tel','(0415)8122071','电话');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('e_mail','fc_fangchan@163.com','电邮');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('head_logo_url','http://localhost:8080/HouseSaleContract_SNAPSHOT/img/cms/sitelogo.png','网站主图标地址');
INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('foot_logo_url','http://localhost:8080/HouseSaleContract_SNAPSHOT/img/cms/housing_authority_footer_logo.png','网站脚图标地址');

INSERT CONTRACT.SYSTEM_PARAM(ID, VALUE, DESCRIPTION) VALUES ('cms_mgr_password','FcCMS001','网站管理密码');

INSERT CONTRACT.ARTICLE_CATEGORY(ID,NAME,PRI,TYPE,DESCRIPTION) VALUES ('welcome','Welcome',0,'Welcome','首页文章');
INSERT CONTRACT.ARTICLE(ID,MAIN_TITLE,SUB_TITLE,CATEGORY,PUBLISH_TIME,FIX_TOP,VIEW_TYPE) VALUES ('welcome','首页文章','请到网站管理中设置首页文章','welcome',now(),false,'HTML');
