USE CONTRACT;


INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('nginx_address','STRING','http://localhost:6699','API服务器地址');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('database_version','STRING','2.0','数据库版本');


INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('OWNER_SHARE_CALC_TYPE','INTEGER','1','按份共有分配方式: 1.按份额, 2.按面积, 3.手动');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('AUTO_CONTRACT_NUMBER','BOOLEAN','TRUE','是否自动生成合同号');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('USE_FINGERPRINT','BOOLEAN','FALSE','是否使用指纹仪');
INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('IMG_SERVER_ADDRESS','STRING','http://192.168.0.123:8090','图片服务器地址');

INSERT CONTRACT.SYSTEM_PARAM(ID,TYPE, VALUE, DESCRIPTION) VALUES ('CONTRACT_LOCATION','STRING','','特殊合同');



CREATE TABLE CONTRACT.SCHOOL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


CREATE TABLE CONTRACT.SELL_AREA
(
	ID varchar(32) NOT NULL,
	NAME varchar(64) NOT NULL,
	DISTRICT varchar(32) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;



CREATE TABLE CONTRACT.NEW_HOUSE_CONTRACT
(
	ID varchar(32) NOT NULL,
	PROJECT_ID varchar(32) NOT NULL,
	SALE_PAY_TYPE varchar(32) NOT NULL,
	PROJECT_CER_NUMBER varchar(100) NOT NULL,
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

UPDATE HOUSE_CONTRACT set PROJECT_CER_NUMBER = '' WHERE PROJECT_CER_NUMBER is null;
UPDATE HOUSE_CONTRACT set PROJECT_ID = '' WHERE PROJECT_ID is null;

INSERT INTO NEW_HOUSE_CONTRACT(ID,PROJECT_ID,SALE_PAY_TYPE,PROJECT_CER_NUMBER) SELECT ID,PROJECT_ID,SALE_PAY_TYPE,PROJECT_CER_NUMBER FROM HOUSE_CONTRACT;


ALTER TABLE CONTRACT.HOUSE_CONTRACT DROP PROJECT_ID;

ALTER TABLE CONTRACT.HOUSE_CONTRACT DROP SALE_PAY_TYPE;

ALTER TABLE CONTRACT.HOUSE_CONTRACT DROP PROJECT_CER_NUMBER;

DROP INDEX HOUSE_CODE ON CONTRACT.HOUSE_CONTRACT;


ALTER TABLE CONTRACT.NEW_HOUSE_CONTRACT
	ADD FOREIGN KEY (ID)
	REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE CONTRACT.BUSINESS_POOL ADD BIRTHDAY DATE NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD SEX VARCHAR(10) NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD TYPE VARCHAR(16) NOT NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD PRI INT NOT NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD POST_CODE VARCHAR(9) NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD ROOT_ADDRESS VARCHAR(50) NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD ADDRESS VARCHAR(200) NULL;

ALTER TABLE CONTRACT.BUSINESS_POOL ADD FINGERPRINT VARCHAR(512) NULL;

ALTER TABLE CONTRACT.BUSINESS_POOL MODIFY PERC DECIMAL(19,4);

ALTER TABLE CONTRACT.BUSINESS_POOL ADD PAPER_COPY_A VARCHAR(32) NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD PAPER_COPY_B VARCHAR(32) NULL;
ALTER TABLE CONTRACT.BUSINESS_POOL ADD PAPER_COPY_INFO VARCHAR(1024) NULL;

ALTER TABLE CONTRACT.HOUSE_CONTRACT ADD HOUSE_AREA DECIMAL(19,4) NULL;
ALTER TABLE CONTRACT.HOUSE_CONTRACT ADD CONTRACT_INDEX VARCHAR(1024) NULL;


UPDATE BUSINESS_POOL set TYPE = 'BUYER';
UPDATE BUSINESS_POOL set PRI = 2;


INSERT INTO BUSINESS_POOL(ID,NAME,ID_TYPE,ID_NO,PHONE,ROOT_ADDRESS,LEGAL_PERSON,ADDRESS,LEGAL_TYPE,CONTRACT,TYPE,PRI) SELECT ID,NAME,ID_TYPE,ID_NO,PHONE,ROOT_ADDRESS,LEGAL_PERSON,ADDRESS,LEGAL_TYPE,ID,'BUYER',1 FROM CONTRACT_OWNER;

CREATE TABLE CONTRACT.POWER_PROXY_PERSON
(
	ID varchar(32) NOT NULL,
	TYPE varchar(16) NOT NULL,
	NAME varchar(50) NOT NULL,
	ID_TYPE varchar(32) NOT NULL,
	ID_NO varchar(100) NOT NULL,
	ROOT_ADDRESS varchar(50),
	BIRTHDAY date,
	SEX varchar(10),
	ADDRESS varchar(200),
	POST_CODE varchar(9),
	PHONE varchar(15) NOT NULL,
	FINGERPRINT varchar(512),
	PAPER_COPY_A varchar(32),
	PAPER_COPY_B varchar(32),
	PAPER_COPY_INFO VARCHAR(1024),
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE CONTRACT.POWER_PROXY_PERSON
	ADD FOREIGN KEY (ID)
	REFERENCES CONTRACT.BUSINESS_POOL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;





CREATE TABLE CONTRACT.OLD_HOUSE_CONTRACT
(
	ID varchar(32) NOT NULL,
	-- 三方合同
	CONTROL boolean NOT NULL COMMENT '三方合同',
	PRIMARY KEY (ID)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

ALTER TABLE CONTRACT.OLD_HOUSE_CONTRACT
	ADD FOREIGN KEY (ID)
REFERENCES CONTRACT.HOUSE_CONTRACT (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

