ALTER TABLE CONTRACT.HOUSE_CONTRACT ADD SALE_PAY_TYPE VARCHAR(32) NOT NULL;
UPDATE HOUSE_CONTRACT hc LEFT JOIN NEW_HOUSE_CONTRACT nhc on hc.ID = nhc.ID set hc.SALE_PAY_TYPE = nhc.SALE_PAY_TYPE;
ALTER TABLE CONTRACT.NEW_HOUSE_CONTRACT DROP SALE_PAY_TYPE;
ALTER TABLE CONTRACT.POWER_PROXY_PERSON DROP PAPER_COPY_A;
ALTER TABLE CONTRACT.POWER_PROXY_PERSON DROP PAPER_COPY_B;
ALTER TABLE CONTRACT.BUSINESS_POOL DROP PAPER_COPY_A;
ALTER TABLE CONTRACT.BUSINESS_POOL DROP PAPER_COPY_B;

ALTER TABLE CONTRACT.SALE_PROXY_PERSON DROP DISABLED;